### ISSUE TITLE
Changed URL

### ISSUE THREAD

**Issue by ArthurusDent** [onSec-fr/Keepass-Enhanced-Security-Configuration#1]
Thanks for the guide!

The URL in this sentence has changed: "On the other hand its popularity leads to a risk since there are [many ways to attack Keepass](https://www.harmj0y.net/blog/redteaming/keethief-a-case-study-in-attacking-keepass-part-2/) nowadays. Furthermore the large number of features increases the potential attack surface."

The correct URL is: https://blog.harmj0y.net/redteaming/keethief-a-case-study-in-attacking-keepass-part-2/

**Comment by onSec-fr** [comment]
Hi,

Thanks for the input.
It seems that the url of the blog has changed. I corrected the link.
